version: '3.1'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - external-network
networks:
  external-network: